import os
names=[]
seqs=[]
for files in os.listdir('fastas/'):
	with open('fastas/'+files) as f:
		for x in f:
			if '>' not in x:
				seqs.append(x.strip())
			else:
				names.append(x.strip().replace('>',''))
#start at 1
interface_indices=[39, 74, 144, 212, 15, 22, 23, 24, 25, 37, 42, 127, 128, 132, 139, 140, 141, 142, 143, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 201, 202, 204, 206, 207, 208, 209, 210, 211, 213, 214, 134]
#start at 8
ting_seqs=[['S153N'], ['T30A','S153N'], ['I138T', 'S153N', 'T180A']]
baker_seqs=['PRDYNPISDTIVKLTNTSDGYSISLYGIGFGPLIITNAHLFRRNNGTLTVTSKHGTFTIENTTTLQLHLIEGRDLVIIKMPKDFPPFPTDLVFREPVEGEKITLVTRNFQTKEPTSEVSDVSSTYPSSDGVFWKHWIPTKDGQCGSPMVSVEDGSIVGIHSASNFTNTNNYFTAVPPDFMDLLTNDSLQKWISGWSLNSDSVEWGGHKVFMDKP', \
'PRDYNPISDTIVLLTNTSDGYSISLYGIGFGPLIITNAHLFRRNNGTLTITSKHGTFTISNTTTLKLHLIEGRDLVLIEMPKDFPPFPTNLVFREPVVGEEIVLVTRNFQTKTPTSEVSDVSTTYPSSDGVFWKHWIPTKDGQCGSPMVSVTDGSIVGIHSASNFTNTNNYFTAVPPDFMRLLTDPSLQKWVSGWSLNSDSVEWGGHKVFMDKP', \
'PRDYNPISSTIVRLTNTSDGHSISLFGIGFGPLIITNAHLFRRNNGTLTITSLHGTFTISNTTTLKLHLIEGRDLVIIKMPKDFPPFPTTLEFREPVVGEDIVLVTRNFQDKDPTSEVSDTSTTEPSSDGVFWKHWIPTKDGQCGSPMVSVSDGSIVGIHSASNFTNTNNYFTAVPPNFMDLLTDPSLQKWISGWSLNADSVDWGGHKVFMDKP', \
'PRDYNPISSTICHLTNESDGHTTSLYGIGFGPFIITNKHLFRRNNGTLLVQSLHGVFKVKNTTTLQQHLIDGRDMIIIRMPKDFPPFPQKLKFREPQREERICLVTTNFQTKSMSSMVSDTSCTFPSSDGIFWKHWIQTKDGQCGSPLVSTRDGFIVGIHSASNFTNTNNYFTSVPKNFMELLTNQEAQQWVSGWRLNADSVLWGGHKVFMDKP', \
'PRDYNPISSTICHLTNESDGHTTSLYGIGFGPFIITNKHLFRRNNGTLLVQSLHGVFKVKNTTTLQQHLIDGRDMIIIRMPKDFPPFPQKLKFREPQREERICLVTTNFQTKSMSSMVSDTSCTFPSSDGIFWKHWIQTKDGQCGSPLVSTRDGFIVGIHSASNFTNTNNYFTSVPKNFMELLTNQEAQQWVSGWRLNADSVLWGGHKVFMVKP', \
'PRDYNPISSTICHLTNESDGHTTSLYGIGFGPFIITNKHLFRRNNGTLLVQSLHGVFKVKNTTTLQQHLIDGRDMIIIRMPKDFPPFPQKLKFREPQREERICLVTTNFQTKSMSSMVSDTSCTFPSSDGIFWKHWIQTKDGQCGNPLVSTRDGFIVGIHSASNFTNTNNYFTSVPKNFMELLTNQEAQQWVSGWRLNADSVLWGGHKVFMVKP', \
'PRDYNPISSTIVHLTNESDGHTTSLYGIGFGPFIITNKHLFRRNNGTLLVQSLHGVFKVKNTTTLQQHLIDGRDMIIIRMPKDFPPFPQKLKFREPQREERIVLVTTNFQTKSMSSMVSDTSSTFPSSDGIFWKHWIQTKDGQCGSPLVSTRDGFIVGIHSASNFTNTNNYFTSVPKNFMELLTNQEAQQWVSGWRLNADSVLWGGHKVFMDKP']

new_seqs=[]
new_names=[]
for a, b in zip(names, seqs):
	ting_ctr=0
	for c in ting_seqs:
		curr_list=list(b)
		for d in c:
			curr_index=int(d[1:-1])
			curr_mut=d[-1]
			if curr_index-7 not in interface_indices:
				curr_list[curr_index-8]=curr_mut
		new_names.append(a+'_ting_'+str(ting_ctr))
		new_seqs.append(''.join(curr_list))
		ting_ctr+=1
	baker_ctr=0
	for c in baker_seqs:
		curr_list=list(b)
		baker_list=list(c)
		index_ctr=1
		for d, e in zip(curr_list, baker_list):
			if d != e and index_ctr not in interface_indices:
				curr_list[index_ctr-1]=e
			index_ctr+=1
		new_names.append(a+'_baker_'+str(baker_ctr))
		new_seqs.append(''.join(curr_list))
		baker_ctr+=1
new_names_nr=[]
new_seqs_nr=[]
for a, b in zip(new_names, new_seqs):
	if b not in new_seqs_nr and b not in seqs:
		new_names_nr.append(a)
		new_seqs_nr.append(b)
print(len(new_seqs))
print(len(new_seqs_nr))
with open('baker_ting_seqs.fa','w') as f:
	for a, b in zip(new_names_nr, new_seqs_nr):
		f.write('>'+a+'\n')
		f.write(b+'\n')










